name: Test Python

description: "Runs tests from reusable Pyhton Tests"

inputs:
  test_path:
    description: "The test Path"
    required: true
  py-version:
    description: "The python version to run the tests on"
    required: true



runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Install ffmpeg
      if: inputs.ffmpeg-required
      uses: FedericoCarboni/setup-ffmpeg@v2
    - name: Set up Python ${{ inputs.py-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.py-version }}
        cache: 'pip'
    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
        fi
        if [ -f "requirements-dev.txt" ]; then
            pip install -r requirements-dev.txt
        fi
    - name: Lint
      shell: bash
      run: |
        flake8 .
    - name: Static type checking
      shell: bash
      run: |
        mypy .
    - name: Run pytest
      shell: bash
      run: pytest --cov=${{ inputs.test_path }} tests/