name: Testing Python Package

description: "Runs linter, static type checking and tests for a Python package."

inputs:
  package-path:
    description: "Specifies the Python package directory for coverage reporting."
    required: true
  py-version:
    description: "Version of Python used to execute the tests."
    required: true
  ffmpeg-required:
    description: "Determines if FFMPEG installation is needed."
    required: false
    default: false
  test-path:
    description: "Directory containing the test files."
    required: false
    default: tests/
  uv-sync-args:
    description: "Optional CLI flags passed to 'uv sync' (e.g., '--extra opt1 --extra opt2')."
    required: false
    default: ""
  playwright-required:
    description: "Determines if playwright installation is needed."
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Install ffmpeg
      if: inputs.ffmpeg-required
      uses: FedericoCarboni/setup-ffmpeg@v2
    - name: Set up Python ${{ inputs.py-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.py-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Install the project
      shell: bash
      run: uv sync --locked --dev ${{ inputs.uv-sync-args }}
    - name: Linting
      shell: bash
      run: uv run flake8 .
    - name: Static type checking
      shell: bash
      run: uv run mypy .
    - name: Install Playwright browsers (Ubuntu)
      if: runner.os == 'Linux' && inputs.playwright-required
      shell: bash
      run: |
        uv pip install --upgrade pip
        uv pip install playwright
        uv run playwright install --with-deps
    - name: Install Playwright browsers (Windows)
      if: runner.os == 'Windows' && inputs.playwright-required
      shell: powershell
      run: |
        uv pip install --upgrade pip
        uv pip install playwright
        uv run playwright install
    - name: Testing
      shell: bash
      run: uv run pytest --cov=${{ inputs.package-path }} ${{ inputs.test-path }}
