name: Test Python

description: "Runs tests from reusable Pyhton Tests"

inputs:
  test_path:
    description: "The test Path"
    required: true
  os:
    description: "The os to run the tests on"
    required: true
  py-version:
    description: "The python version to run the tests on"
    required: true

runs:
  using: "composite"
  steps:
      - name: Run Python tests on multiple OS and Python versions
        uses: platomo/GitHub-workflows/.github/workflows/reusable-python-tests.yml@main
        with:
          os: ${{ inputs.os }}
          py-version: ${{ inputs.py-version }}
          test_path:  ${{ inputs.test_path }}