name: Testing Python Package

description: "Runs linter, static type checking and tests for a Python package."

inputs:
  package-path:
    description: "Specifies the Python package directory for coverage reporting."
    required: true
  py-version:
    description: "Version of Python used to execute the tests."
    required: true
  ffmpeg-required:
    description: "Determines if FFMPEG installation is needed."
    required: false
    default: false
  test-path:
    description: "Directory containing the test files."
    required: false
    default: tests/

runs:
  using: composite
  steps:
    - name: Install ffmpeg
      if: inputs.ffmpeg-required
      uses: FedericoCarboni/setup-ffmpeg@v2
    - name: Set up Python ${{ inputs.py-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.py-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Install Python dependencies
      shell: bash
      run: |
        uv venv
        if [ -f "requirements.txt" ]; then
            uv pip install -r requirements.txt
        fi
        if [ -f "requirements-dev.txt" ]; then
            uv pip install -r requirements-dev.txt
        fi
        if [ -f "pyproject.toml" ]; then
            uv pip install . --all-extras -r pyproject.toml
        fi
    - name: debugging
      shell: bash
      run: ls -lha
    - name: Linting
      shell: bash
      run: |
        .venv/bin/flake8 .
    - name: Static type checking
      shell: bash
      run: |
        .venv/bin/mypy .
    - name: Testing
      shell: bash
      run: .venv/bin/pytest --cov=${{ inputs.package-path }} ${{ inputs.test-path }}
