name: Testing Python Package

description: "Runs linter, static type checking and tests for a Python package."

inputs:
  package-path:
    description: "Path to determine test coverage."
    required: true
  py-version:
    description: "Python version to run the tests on."
    required: true
  ffmpeg-required:
    description: "Bool to check if FFMPEG needs to be installed."
    required: false
    default: false
    type: boolean
  test-path:
    description: "Path to the test files."
    required: false
    default: tests/

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Install ffmpeg
      if: inputs.ffmpeg-required
      uses: FedericoCarboni/setup-ffmpeg@v2
    - name: Set up Python ${{ inputs.py-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.py-version }}
        cache: "pip"
    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
        fi
        if [ -f "requirements-dev.txt" ]; then
            pip install -r requirements-dev.txt
        fi
    - name: Linting
      shell: bash
      run: |
        flake8 .
    - name: Static type checking
      shell: bash
      run: |
        mypy .
    - name: Testing
      shell: bash
      run: pytest --benchmark-skip --cov=${{ inputs.package-path }} ${{ inputs.test-path }}
