# Copyright (c) 2021 Vincent A. Cicirello
# MIT License
# https://gist.github.com/cicirello/ade1d559a89104140557389365154bc1

name: Update Major Release Tag

on:
  release:
    types: [created]

jobs:
  movetag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get major version num and update tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR=${VERSION%%.*}
          git tag -fa "${MAJOR}" -m 'Update major version tag'
          git push origin "${MAJOR}" --force
